### ISSUE TITLE
NOPTMAX=0 output

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#23]
It seems that the `iobj` is not written when NOPTMAX=0. For Monte Carlo type applications, it would be really useful to write this out since the `iobj` format is easier to read, programmatically, than the `rec` file.

**Comment by jtwhite79** [comment]
you are right - it should write the iobj regardless of ``noptmax``.  I'll work on it.

**Comment by jtwhite79** [comment]
done
