### ISSUE TITLE
opt_skip_final

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#24]
Saw the option `opt_skip_final` in your Freyberg example code. Can add that to the README file to explain that it's there?

**Comment by jtwhite79** [comment]
I will...eventually.  Right now, its a dev option to support (really interesting) dataworth in OUU: if you set ``++base_jacobian``, ``++hotstart_resfile``, and ``++opt_skip_final`` and ``noptmax`` = 0, then it activates a super secret option where the LP problem is solved and optimal phi and dec vars are written but no model runs are undertaken (WAT?!).  So ``pestpp-opt`` starts up, reads these files, calls the LP solver and quits.

**Comment by mnfienen** [comment]
I like it! kewl.....makes sense why it's not documented yet.
