### ISSUE TITLE
Small bug in pestpp-opt output

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#25]
Looks like the REI for (for example) the first iteration from `pestpp-opt` is being labelled `<casename>.jcb.1.rei` rather than just `<casename>.1.rei`

**Comment by jtwhite79** [comment]
That is actually on purpose.  The casename.jcb.1.rei file is the residuals from the base run used to fill the response matrix - it's the file needed for the "hotstart" . I'm open to other naming suggestions...

**Comment by mnfienen** [comment]
Ah OK - missed that page in the manual ;). The naming is fine but I just didn't know the reasoning.
