### ISSUE TITLE
mismatch of control file on master and worker

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#26]
I thought that, if a worker is started calling a control file, it will only run properly if the filename matches the control file that the master is running. Is this check for consistency made? It seems not.

**Comment by jtwhite79** [comment]
you are right - there is no checking of control file name between workers and master.  I personally don't think the name checking is as important as consistency of par and obs names. I did some testing and if the worker is missing (or has an extra) parameter or observation, the worker will object, but only once it gets to the processing of templates or instructions (which in the case of instructions could be after the model has been run!).  @dwelter - this is something that should be checked when the workers are being initialized?  We are already passing the par and obs name vectors to the workers during the initialization, so shouldn't take much for a quick set compare

**Comment by mnfienen** [comment]
cool - I agree that most of the time as long as the pars and obs line up probably the rest is consistent enough that the master handles it all fine. Just a thought though to potentially avoid bumbles.
