### ISSUE TITLE
PESTPP-OPT Capitalization issue

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#27]
It appears that PESTPP-OPT is internally capitalizing decision variables. If they are read from an external objective function file (on a Mac), PESTPP-OPT reports that the objective function doesn't match the decision variables. However, if the DVs are capitalized in the external file and lowercase in the PST file, they work. If they are capitalized in both places they work. But, if lowercase in both places, no dice. 

Doesn't appear to be an issue on Windows....

**Comment by jtwhite79** [comment]
Hey Mike - I can't reproduce this issue on mac using the latest ``develop`` branch builds.  Can you double check that you are using latest and (hopefully) greatest?
