### ISSUE TITLE
Continuing even after failed upgrades

### ISSUE THREAD

**Issue by mnfienen** [dwelter/pestpp#30]
We are running a problem where all the upgrades (lambda runs) are failing due to timing out. We can certainly extend the overdue allowance so they don't time out, but in the meantime, the behavior is as follows:
0) run a Jacobian
1) attempt upgrades
2) all upgrade lambda runs fail
3) try new jacobian with last good parameters 
4) repeat until number of nonimproving iterations is reached (and because no upgrade happens, that PHI is the same all the time).

Suggested behavior: If all upgrade runs fail, bomb out and prominently report that they failed

**Comment by jtwhite79** [comment]
Agree with suggested behavior.  Will add to 4.0.12

**Comment by jtwhite79** [comment]
Done.  the one catch is that if all upgrades fail for a super par iter, then it triggers a regression to base par iter. If all upgrades fail for a base par iter, bomb.
