### ISSUE TITLE
pestpp-ies error writing model input files from template files

### ISSUE THREAD

**Issue by dpphat** [dwelter/pestpp#38]
Hi all.
I am having an issue in which I am getting the following error:

**model input/output error: error writing model input files from template files internal error condition has arisen while attempting to write current value of parameter to model input file**

If I run pestpp-ies with NOPTMAX = 0, I do not get this error and the model runs as expected. When I set NOPTMAX to 3 (or any other positive integer) I get this error. The error causes the model to abort and it retries. 

Any guidance related to how to debug/resolve the issue is much appreciated.
Thanks so much.
Dan

**Comment by jtwhite79** [comment]
@dpphat can you post this issue at github.com/usgs/pestpp with the PST tpl and ins files?  I'll check it out.

**Comment by dpphat** [comment]
Thanks so much Jeremy. 
I have added an issue to github.com/usgs/pestpp with the template and instruction files.
I will close the issue on this dwelter/pestpp page.
