### ISSUE TITLE
Why can't I find the PSO code ?

### ISSUE THREAD

**Issue by alex520** [dwelter/pestpp#9]
Excuse me. I came here from the USGS website. When I read this [article](https://pubs.usgs.gov/tm/07/c12/tm7c12.pdf),  I found the "PEST++ THIRD PARTY APPLICATIONS Particle Swarm Optimization". But I couldn't find anything about PSO in that article. 

Is that article a full article ? And could you tell me where I can find the PSO RELATED information ?

Looking forward to your reply.

**Comment by jtwhite79** [comment]
The PSO application is being developed by Adam Siade at the University of Western Australia, Perth.  He allowed us to include his code in the PEST++ project b/c it using the YAMR run manager.  The code is in the ``src/projects/pestpp-pso/`` directory.  I believe it is still under development.

**Comment by alex520** [comment]
Thanks!
